# Generated by Django 4.2.26 on 2025-12-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadjob',
            name='params',
            field=models.TextField(blank=True, null=True),
        ),
    ]
