# Generated by Django 4.2.26 on 2025-11-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='storage_quota',
            field=models.BigIntegerField(default=53687091200, verbose_name='存储限额（字节）'),
        ),
    ]
