# Generated by Django 4.2.14 on 2025-11-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal', 'Internal'), ('Restricted', 'Restricted')], default='Internal', max_length=20, verbose_name='访问级别'),
        ),
        migrations.AddField(
            model_name='file',
            name='checksum',
            field=models.CharField(blank=True, help_text='文件MD5校验和', max_length=64, verbose_name='校验和'),
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, help_text='文件详细描述', verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='file',
            name='document_type',
            field=models.CharField(choices=[('Paper', 'Paper'), ('Protocol', 'Protocol'), ('Dataset', 'Dataset'), ('Code', 'Code')], default='Dataset', max_length=20, verbose_name='文档类型'),
        ),
        migrations.AddField(
            model_name='file',
            name='experiment_type',
            field=models.CharField(blank=True, choices=[('RNA-seq', 'RNA-seq'), ('WGS', 'Whole Genome Sequencing'), ('scRNA-seq', 'Single Cell RNA-seq'), ('MS', 'Mass Spectrometry'), ('ChIP-seq', 'ChIP-seq'), ('ATAC-seq', 'ATAC-seq'), ('other', 'Other')], max_length=50, verbose_name='实验类型'),
        ),
        migrations.AddField(
            model_name='file',
            name='extracted_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='从文件自动提取的元数据', verbose_name='提取的元数据'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_format',
            field=models.CharField(choices=[('FASTQ', 'FASTQ'), ('FASTA', 'FASTA'), ('VCF', 'VCF'), ('BAM', 'BAM'), ('PDF', 'PDF'), ('CSV', 'CSV'), ('py', 'Python'), ('ipynb', 'Jupyter Notebook'), ('txt', 'Text'), ('other', 'Other')], default='other', max_length=20, verbose_name='文件格式'),
        ),
        migrations.AddField(
            model_name='file',
            name='organism',
            field=models.CharField(blank=True, help_text='如 Homo sapiens', max_length=200, verbose_name='物种'),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.CharField(default='', help_text='项目名或课题号', max_length=200, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='file',
            name='qc_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('passed', 'Passed'), ('failed', 'Failed'), ('pending', 'Pending')], default='unknown', max_length=20, verbose_name='质控状态'),
        ),
        migrations.AddField(
            model_name='file',
            name='search_vector',
            field=models.TextField(blank=True, help_text='用于全文搜索的文本', verbose_name='搜索向量'),
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.TextField(blank=True, help_text='用逗号分隔的标签', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='', help_text='文件的描述性标题', max_length=500, verbose_name='文件标题'),
        ),
        migrations.AddField(
            model_name='file',
            name='uploader',
            field=models.CharField(default='', help_text='上传者姓名', max_length=100, verbose_name='上传者'),
        ),
    ]
