# Generated by Django 4.2.14 on 2025-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_file_access_level_file_checksum_file_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_format',
            field=models.CharField(choices=[('FASTQ', 'FASTQ'), ('FASTA', 'FASTA'), ('VCF', 'VCF'), ('BAM', 'BAM'), ('SAM', 'SAM'), ('BED', 'BED'), ('GTF', 'GTF'), ('GFF', 'GFF'), ('PDF', 'PDF'), ('DOC', 'Word Document'), ('DOCX', 'Word Document'), ('PPT', 'PowerPoint'), ('PPTX', 'PowerPoint'), ('RTF', 'Rich Text Format'), ('CSV', 'CSV'), ('TSV', 'TSV'), ('XLS', 'Excel'), ('XLSX', 'Excel'), ('JSON', 'JSON'), ('XML', 'XML'), ('YAML', 'YAML'), ('SQL', 'SQL'), ('py', 'Python'), ('ipynb', 'Jupyter Notebook'), ('R', 'R Script'), ('Rmd', 'R Markdown'), ('js', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('sh', 'Shell Script'), ('pl', 'Perl'), ('php', 'PHP'), ('rb', 'Ruby'), ('go', 'Go'), ('rs', 'Rust'), ('swift', 'Swift'), ('kt', 'Kotlin'), ('scala', 'Scala'), ('txt', 'Text'), ('md', 'Markdown'), ('log', 'Log File'), ('conf', 'Configuration'), ('ini', 'INI File'), ('cfg', 'Config File'), ('jpg', 'JPEG Image'), ('jpeg', 'JPEG Image'), ('png', 'PNG Image'), ('gif', 'GIF Image'), ('bmp', 'BMP Image'), ('tiff', 'TIFF Image'), ('svg', 'SVG Image'), ('webp', 'WebP Image'), ('ico', 'Icon'), ('mp3', 'MP3 Audio'), ('wav', 'WAV Audio'), ('flac', 'FLAC Audio'), ('aac', 'AAC Audio'), ('ogg', 'OGG Audio'), ('m4a', 'M4A Audio'), ('mp4', 'MP4 Video'), ('avi', 'AVI Video'), ('mov', 'MOV Video'), ('wmv', 'WMV Video'), ('flv', 'FLV Video'), ('mkv', 'MKV Video'), ('webm', 'WebM Video'), ('m4v', 'M4V Video'), ('zip', 'ZIP Archive'), ('rar', 'RAR Archive'), ('7z', '7-Zip Archive'), ('tar', 'TAR Archive'), ('gz', 'GZIP Archive'), ('bz2', 'BZIP2 Archive'), ('xz', 'XZ Archive'), ('other', 'Other')], default='other', max_length=20, verbose_name='文件格式'),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_method',
            field=models.CharField(max_length=50, verbose_name='Upload Method'),
        ),
    ]
