# Generated by Django 5.2.7 on 2025-10-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_folder_file_parent_folder_alter_file_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='file_upload.folder'),
        ),
    ]
