# Generated by Django 4.2.26 on 2025-11-18 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_organization_membership'),
        ('file_upload', '0003_alter_file_file_format_alter_file_upload_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_download', models.BooleanField(default=True)),
                ('can_edit_metadata', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='file_upload.file')),
                ('shared_to_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_file_shares', to='authentication.organization')),
                ('shared_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_file_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文件共享',
                'verbose_name_plural': '文件共享',
            },
        ),
    ]
