# Generated by Django 4.2.26 on 2025-11-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0006_alter_file_id_alter_fileshare_id_alter_folder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公开可见'),
        ),
    ]
