"""
Django settings for file_project project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1ai#)@_az=1a-zwtlq4e4#m#@*^84w#qp&!r+7&822ns_6^70d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '222.29.189.123']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'file_upload',
    'file_download',
    'authentication',
    'ml_interface',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'file_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # expose org management visibility for owners
                'authentication.context_processors.management_visibility',
            ],
        },
    },
]

WSGI_APPLICATION = 'file_project.wsgi.application'

# Custom User Model
AUTH_USER_MODEL = 'authentication.CustomUser'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'authentication.validators.ComplexPasswordValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# 为避免与 Vite 中用于 Cellxgene 的 '/static/' 代理冲突，
# 将 Django 静态文件前缀调整为 '/api/static/'，这样通过开发服务器访问
# 时会随 '/api' 一并代理到后端 8020。
STATIC_URL = '/api/static/'
STATICFILES_DIRS = [
    p for p in [
        os.path.join(BASE_DIR, "static"),
        os.path.join(BASE_DIR, "waves-core-ui", "img"),
        # 引入已有的 DRF 静态资源目录，供本地 Bootstrap/jQuery 使用
        os.path.join(BASE_DIR, "Django-Vue3-Admin", "backend", "static"),
    ] if os.path.isdir(p)
]

# specify media root for user uploaded files,
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}

# Primary key type (suppress auto-created PK warnings on Django 4.x)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    # Vite 开发服务器端口
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = True  # Only for development

# CORS headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF settings for API
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    # 允许 Vite 开发服务器作为可信来源
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    # 允许服务器外网地址访问
    "http://222.29.189.123:5173",
    "http://222.29.189.123:8020",
]

# NCBI integration defaults
# Increase default NCBI max download size to 100 GiB to allow large ENA/NCBI FASTQ runs
NCBI_MAX_DOWNLOAD_BYTES = int(os.environ.get('NCBI_MAX_DOWNLOAD_BYTES', 100 * 1024 * 1024 * 1024))  # 100 GiB
NCBI_HTTP_TIMEOUT = int(os.environ.get('NCBI_HTTP_TIMEOUT', 120))

# ===== File upload/download custom settings =====
# 最大上传尺寸（字节），前端文案将与此保持一致
MAX_UPLOAD_SIZE_BYTES = 100 * 1024 * 1024 * 1024  # 100GB

# Django文件上传大小限制配置
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024 * 1024  # 100GB
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024 * 1024  # 100GB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # 增加字段数量限制

# Cellxgene 数据目录（用于前端一键预览的文件桥接）
# 可通过环境变量 CELLXGENE_DATA_DIR 覆盖默认目录
CELLXGENE_DATA_DIR = os.environ.get('CELLXGENE_DATA_DIR', os.path.join(BASE_DIR, 'cellxgene_data'))
CELLXGENE_CMD = os.environ.get('CELLXGENE_CMD', os.path.join(BASE_DIR, '.venv-cellxgene/bin/cellxgene'))
CELLXGENE_HOST = os.environ.get('CELLXGENE_HOST', '0.0.0.0')
CELLXGENE_PORT = int(os.environ.get('CELLXGENE_PORT', '5005'))
CELLXGENE_PID_FILE = os.environ.get('CELLXGENE_PID_FILE', os.path.join(BASE_DIR, '.pids', 'cellxgene.pid'))
CELLXGENE_LOG_FILE = os.environ.get('CELLXGENE_LOG_FILE', os.path.join(BASE_DIR, 'logs', 'cellxgene.log'))
CELLXGENE_AUTO_RESTART = os.environ.get('CELLXGENE_AUTO_RESTART', 'true').lower() == 'true'
CELLXGENE_PYTHON = os.environ.get('CELLXGENE_PYTHON', os.path.join(os.path.dirname(CELLXGENE_CMD), 'python'))

# Allow embedding pages in same-origin frames for IDE preview
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Downloader binary path configuration
# If not provided via environment, default to the legacy deployment path.
LND_PATH = os.environ.get('LND_PATH', '/home/mosserver/software/linuxnd')
